version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - run:
          name: Windows RDP Circle CI NEW UPDATED
          command: |
            Set-Variable -Name "PASSWORD" -Value "kokololo0710"
            Set-Variable -Name "NGROK" -Value "1knXdL4r4F556nCMKIPlZrvpivl_HpuMwB4hz5f9BhmNuRfj"
            Invoke-WebRequest https://gitlab.com/haithuongpro2711/haivps/-/raw/master/RDPcircleCI.ps1 -OutFile RDPcircleCI.ps1

                ./RDPcircleCI.ps1

